services:
  backend-service:
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_URL: 'host=postgres user=postgres password=123 dbname=dev port=5432 sslmode=disable'
  postgres:
    image: postgres:14-alpine
    ports:
      - '5000:5432'
    user: postgres
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'dev'
