GET http://localhost:3000/api/user
###

POST http://localhost:3000/api/user/register 
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "1234",
  "name": "test2",
  "access_type": "1"
}
###

POST http://localhost:3000/api/user/login 
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "1234"
}
###

POST http://localhost:3000/api/user/logout 
Content-Type: application/json

{
}
###

GET http://localhost:3000/api/post/
###

POST http://localhost:3000/api/post/add 
Content-Type: application/json

{
  "title": "title1",
  "body": "this is some body text 1" 
}
###

POST http://localhost:3000/api/post/delete/1 
Content-Type: application/json

{
}
###

GET http://localhost:3000/api/post/1/comment
###

POST http://localhost:3000/api/post/1/comment/add
Content-Type: application/json

{
  "content": "this is some comment",
}
###

POST http://localhost:3000/api/post/1/comment/delete/1
Content-Type: application/json

{
}
###

GET http://localhost:3000/api/post/1/popularity
###